feat(ci): adjust the workflow so it can be reused (#7)
* fix(ci): avoid set-output and add a debug

* debug

* remove the debug

* chore(ci): prioritize branch over sha

* put the debug back

* chore(ci): add the secret intputs for the reusable workflow

* chore:ci skip building when it's a workflow dispatch call

* debug

* chore(ci): don't build if test_type is set

* debug

* chore: remove debug

* fix(tests): fix the tests so they match the shorter name

* chore(aws-quota): hack to avoid the aws cloudtrail quota

* fix(Make): don't force the aws check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,16 +11,31 @@ on:
     inputs:
       test_type:
         description: 'Type of test: terraform or cloudformation'
-        required: false
-        default: 'terraform'
+        required: true
         type: 'string'
       code_sha:
         description: 'SHA of the terraform or cloudformation code to checkout'
-        required: false
+        required: true
         type: 'string'
+    secrets:
+      OBSERVE_CUSTOMER:
+        required: true
+      OBSERVE_TOKEN:
+        required: true
+      OBSERVE_DOMAIN:
+        required: false
+      AWS_ACCESS_KEY_ID:
+        required: true
+      AWS_SECRET_ACCESS_KEY:
+        required: true
+      AWS_SESSION_TOKEN:
+        required: false
+      AWS_REGION:
+        required: false
 
 env:
   USER: gha-${{ github.run_id }}
+  AWS_TEST_KITCHEN_REPO: aws-test-kitchen
 
 jobs:
   permission_check:
@@ -49,10 +64,11 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
       with:
-        repository: ${{ github.repository_owner }}/aws-test-kitchen
+        repository: ${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}
         submodules: true
     
     - name: Login to GitHub Container Registry
+      if: ${{ inputs.test_type == '' }}
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
@@ -60,26 +76,33 @@ jobs:
         password: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Set up Docker Buildx
+      if: ${{ inputs.test_type == '' }}
       uses: docker/setup-buildx-action@v2
 
     - name: Metadata for Docker Image
       id: docker_metadata
       uses: docker/metadata-action@v4
       with:
-        images: ghcr.io/${{ github.repository }}
+        images: ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}
         tags: |
-          type=sha,priority=1001
-          type=ref,event=branch
+          type=sha
+          type=ref,event=branch,priority=1001
           type=raw,value=latest,enable={{is_default_branch}}
 
     - name: Set IMAGE_NAME environment variable
       id: set_output_image_name
       run: |
-        IMAGE_NAME=$(echo "${DOCKER_METADATA_OUTPUT_TAGS}" | head -n 1)
+        if [[ "${{ inputs.test_type }}" != "" ]]; then
+          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:main"
+        else
+          IMAGE_NAME=$(echo "${DOCKER_METADATA_OUTPUT_TAGS}" | head -n 1)
+        fi
         echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
         echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
         
+        
     - name: Build docker image
+      if: ${{ inputs.test_type == '' }}
       uses: docker/build-push-action@v4
       with:
         context: .
@@ -89,23 +112,25 @@ jobs:
         labels: ${{ steps.docker_metadata.outputs.labels }}
         cache-from: |
           type=gha
-          ghcr.io/${{ github.repository }}:latest
-          ghcr.io/${{ github.repository }}:main
-          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:latest
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:main
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:${{ github.ref_name }}
         cache-to: type=gha,mode=max
 
   determine-provider:
     runs-on: ubuntu-latest
     outputs:
       providers: ${{steps.set-providers.outputs.providers}}
-
+  
     steps:
     - id: set-providers
       run: |
         if [[ "${{ github.event_name }}" == "pull_request" || "${{ github.event_name }}" == "push" ]]; then
-          echo "::set-output name=providers::[\"cloudformation\", \"terraform\"]"
+          echo "providers=[\"cloudformation\", \"terraform\"]" >> $GITHUB_ENV
+          echo "providers=[\"cloudformation\", \"terraform\"]" >> $GITHUB_OUTPUT
         else
-          echo "::set-output name=providers::[\"${{ github.event.inputs.test_type }}\"]"
+          echo "providers=[\"${{ github.event.inputs.test_type }}\"]" >> $GITHUB_ENV
+          echo "providers=[\"${{ github.event.inputs.test_type }}\"]" >> $GITHUB_OUTPUT
         fi
 
   test:
@@ -130,7 +155,7 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
       with:
-        repository: ${{ github.repository_owner }}/aws-test-kitchen-public
+        repository: ${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}
         submodules: true
 
     - name: Checkout Terraform SHA
@@ -157,15 +182,17 @@ jobs:
 
     - name: Metadata for Docker Image
       id: docker_metadata
+      if: ${{ inputs.test_type == '' }}
       uses: docker/metadata-action@v4
       with:
-        images: ghcr.io/${{ github.repository }}
+        images: ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}
         tags: |
-          type=sha,priority=1001
-          type=ref,event=branch
+          type=sha
+          type=ref,event=branch,priority=1001
           type=raw,value=latest,enable={{is_default_branch}}
         
-    - name: Build docker image
+    - name: Build docker image (from cache)
+      if: ${{ inputs.test_type == '' }}
       uses: docker/build-push-action@v4
       with:
         context: .
@@ -175,10 +202,28 @@ jobs:
         labels: ${{ steps.docker_metadata.outputs.labels }}
         cache-from: |
           type=gha
-          ghcr.io/${{ github.repository }}:latest
-          ghcr.io/${{ github.repository }}:main
-          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:latest
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:main
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:${{ github.ref_name }}
         cache-to: type=gha,mode=max
+
+    - name: Pull Docker image
+      if: ${{ inputs.test_type != '' }}
+      run: docker pull $IMAGE_NAME
+
+    - name: Check AWS Quota
+      run: |
+        attempts=0
+        until make check_aws_quota; do
+          if [ $attempts -ge 10 ]; then
+            echo "Exceeded maximum retries for quota check."
+            exit 1
+          fi
+          echo "Failed to meet quota. Retrying in 2 minutes..."
+          sleep 120
+          attempts=$((attempts + 1))
+        done
+    
 
     - name: Setup Infra and Run spec tests
       run: make docker/test
@@ -195,7 +240,7 @@ jobs:
   push:
     runs-on: ubuntu-latest
     needs: [permission_check, build, test]
-    if: needs.permission_check.outputs.can-write == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
+    if: ${{ inputs.test_type == '' }} && needs.permission_check.outputs.can-write == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
     permissions:
       contents: write
       packages: write
@@ -204,7 +249,7 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
       with:
-        repository: ${{ github.repository_owner }}/aws-test-kitchen-public
+        repository: ${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}
         submodules: true
     
     - name: Login to GitHub Container Registry
@@ -221,10 +266,10 @@ jobs:
       id: docker_metadata
       uses: docker/metadata-action@v4
       with:
-        images: ghcr.io/${{ github.repository }}
+        images: ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}
         tags: |
-          type=sha,priority=1001
-          type=ref,event=branch
+          type=sha
+          type=ref,event=branch,priority=1001
           type=raw,value=latest,enable={{is_default_branch}}
 
     - name: Push Docker images
@@ -237,7 +282,7 @@ jobs:
         labels: ${{ steps.docker_metadata.outputs.labels }}
         cache-from: |
           type=gha
-          ghcr.io/${{ github.repository }}:latest
-          ghcr.io/${{ github.repository }}:main
-          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:latest
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:main
+          ghcr.io/${{ github.repository_owner }}/${{ env.AWS_TEST_KITCHEN_REPO }}:${{ github.ref_name }}
         cache-to: type=gha,mode=max
